[workspace]
resolver = "2"
members = [
    "crates/embedded-dsp",
    "crates/embedded-dsp-studio",
]

[workspace.package]
version = "0.5.1"
edition = "2024"
rust-version = "1.93"
authors = ["Gerzain Mata <leftger@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/leftger/embedded-dsp"
readme = "README.md"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.dependencies]
embedded-dsp = { path = "crates/embedded-dsp", version = "0.5.1", default-features = false }
fixed = { version = "1.31.0", default-features = false }
libm = { version = "0.2.11" }
defmt = { version = "1.1", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
nalgebra = { version = "0.35", default-features = false, features = ["libm"] }
bytemuck = { version = "1.24.0", default-features = false, features = ["derive"] }
quickcheck = { version = "1.0.3", default-features = false }
quickcheck_macros = { version = "1.0.0" }

eframe = { version = "0.36", default-features = true }
egui_extras = { version = "0.36" }
rfd = "0.17"
log = "0.4"
