ignore:
  - "benches/**"
  - "examples/**"
  - "embedded-dsp-docs.zip"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 60%
        threshold: 1%
