//! MCU C & Rust Codegen View for Target Deployment.
//!
//! Exports zero-allocation, static buffer code for microcontrollers (Cortex-M, RISC-V, ESP32)
//! matching the exact filter design tuned in the studio.

use crate::state::{ProcessorConfig, ProcessorMode, StudioState};
use eframe::egui;
use embedded_dsp::filter_design::{
    biquad_bandpass_coeffs, biquad_highpass_coeffs, biquad_lowpass_coeffs, biquad_notch_coeffs,
    biquad_peaking_coeffs,
};

#[derive(Default)]
pub struct CodegenView {
    pub target_language: TargetLanguage,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TargetLanguage {
    #[default]
    RustNoStd,
    CmsisDspC,
}

impl CodegenView {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn show(&mut self, ui: &mut egui::Ui, state: &StudioState) {
        ui.horizontal(|ui| {
            ui.heading("⚡ 6. Zero-Allocation MCU Codegen");
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                ui.selectable_value(
                    &mut self.target_language,
                    TargetLanguage::RustNoStd,
                    "🦀 no_std Rust",
                );
                ui.selectable_value(
                    &mut self.target_language,
                    TargetLanguage::CmsisDspC,
                    "⚙️ CMSIS-DSP C",
                );
            });
        });

        ui.add_space(4.0);
        ui.label(
            "Export ready-to-flash, zero-allocation code tailored for microcontrollers (ARM Cortex-M, \
            RISC-V, ESP32). Copy directly into your firmware project.",
        );
        ui.add_space(8.0);

        let code = match self.target_language {
            TargetLanguage::RustNoStd => generate_rust_code(&state.proc_a, state.sample_rate),
            TargetLanguage::CmsisDspC => generate_c_code(&state.proc_a, state.sample_rate),
        };

        ui.horizontal(|ui| {
            if ui.button("📋 Copy Code to Clipboard").clicked() {
                ui.ctx().copy_text(code.clone());
            }
        });

        ui.add_space(6.0);

        egui::ScrollArea::vertical().show(ui, |ui| {
            ui.add(
                egui::TextEdit::multiline(&mut code.as_str())
                    .font(egui::TextStyle::Monospace)
                    .desired_width(f32::INFINITY)
                    .desired_rows(22)
                    .interactive(false),
            );
        });
    }
}

pub fn generate_rust_code(config: &ProcessorConfig, sample_rate: f32) -> String {
    match config.mode {
        ProcessorMode::SvfLowpass
        | ProcessorMode::SvfHighpass
        | ProcessorMode::SvfBandpass
        | ProcessorMode::SvfNotch
        | ProcessorMode::SvfPeak => {
            let res = (1.0 / (2.0 * config.q.max(0.1))).clamp(0.01, 1.0);
            let method = match config.mode {
                ProcessorMode::SvfHighpass => "highpass",
                ProcessorMode::SvfBandpass => "bandpass",
                ProcessorMode::SvfNotch => "notch",
                ProcessorMode::SvfPeak => "peak",
                _ => "lowpass",
            };
            format!(
                r#"//! Generated by embedded-dsp studio for no_std MCU deployment
//! Algorithm: {:?} (Andrew Simper 2x oversampled SVF)
//! Sample Rate: {:.0} Hz | Cutoff: {:.1} Hz | Resonance: {:.3}

#![no_std]

use embedded_dsp::svf::StateVariableFilter;

pub struct FilterPipeline {{
    svf: StateVariableFilter,
}}

impl FilterPipeline {{
    pub fn new() -> Self {{
        let mut svf = StateVariableFilter::new({:.1});
        svf.set_cutoff({:.1});
        svf.set_resonance({:.3});
        Self {{ svf }}
    }}

    pub fn process_sample(&mut self, x: f32) -> f32 {{
        self.svf.process(x);
        self.svf.{}()
    }}

    pub fn process_block(&mut self, input: &[f32], output: &mut [f32]) {{
        for (i, o) in input.iter().zip(output.iter_mut()) {{
            self.svf.process(*i);
            *o = self.svf.{}();
        }}
    }}
}}
"#,
                config.mode,
                sample_rate,
                config.cutoff_hz,
                res,
                sample_rate,
                config.cutoff_hz,
                res,
                method,
                method,
            )
        }
        _ => {
            let coeffs = match config.mode {
                ProcessorMode::BiquadHighpass => {
                    biquad_highpass_coeffs(config.cutoff_hz, sample_rate, config.q)
                }
                ProcessorMode::BiquadBandpass => {
                    biquad_bandpass_coeffs(config.cutoff_hz, sample_rate, config.q)
                }
                ProcessorMode::BiquadNotch => {
                    biquad_notch_coeffs(config.cutoff_hz, sample_rate, config.q)
                }
                ProcessorMode::BiquadPeaking => {
                    biquad_peaking_coeffs(config.cutoff_hz, sample_rate, config.q, config.gain_db)
                }
                _ => biquad_lowpass_coeffs(config.cutoff_hz, sample_rate, config.q),
            };

            format!(
                r#"//! Generated by embedded-dsp studio for no_std MCU deployment
//! Algorithm: {:?}
//! Sample Rate: {:.0} Hz | Cutoff: {:.1} Hz | Q: {:.3}

#![no_std]

use embedded_dsp::filtering::{{biquad_cascade_df1_f32, BiquadCascadeInstanceF32}};

// Precomputed Direct Form I Biquad coefficients: [b0, b1, b2, a1, a2]
pub static BIQUAD_COEFFS: [f32; 5] = [
    {:.8}f32, // b0
    {:.8}f32, // b1
    {:.8}f32, // b2
    {:.8}f32, // a1
    {:.8}f32, // a2
];

pub struct FilterPipeline {{
    state: [f32; 4],
}}

impl FilterPipeline {{
    pub const fn new() -> Self {{
        Self {{
            state: [0.0; 4],
        }}
    }}

    pub fn process_block(&mut self, input: &[f32], output: &mut [f32]) {{
        let mut instance = BiquadCascadeInstanceF32::init(1, &BIQUAD_COEFFS, &mut self.state);
        biquad_cascade_df1_f32(&mut instance, input, output);
    }}
}}
"#,
                config.mode,
                sample_rate,
                config.cutoff_hz,
                config.q,
                coeffs[0],
                coeffs[1],
                coeffs[2],
                coeffs[3],
                coeffs[4],
            )
        }
    }
}

pub fn generate_c_code(config: &ProcessorConfig, sample_rate: f32) -> String {
    match config.mode {
        ProcessorMode::SvfLowpass
        | ProcessorMode::SvfHighpass
        | ProcessorMode::SvfBandpass
        | ProcessorMode::SvfNotch
        | ProcessorMode::SvfPeak => {
            let res = (1.0 / (2.0 * config.q.max(0.1))).clamp(0.01, 1.0);
            let out_member = match config.mode {
                ProcessorMode::SvfHighpass => "high",
                ProcessorMode::SvfBandpass => "band",
                ProcessorMode::SvfNotch => "notch",
                ProcessorMode::SvfPeak => "band",
                _ => "low",
            };
            format!(
                r#"/* Generated by embedded-dsp studio for Embedded C (ARM Cortex-M / RISC-V)
 * Algorithm: {:?} (Simper 2x oversampled SVF)
 * Sample Rate: {:.0} Hz | Cutoff: {:.1} Hz | Resonance: {:.3}
 */

#include <stdint.h>
#include <math.h>

typedef struct {{
    float low, high, band, notch;
    float freq, damp;
}} svf_filter_t;

static svf_filter_t g_svf;

void svf_init(float sample_rate, float cutoff, float resonance) {{
    g_svf.low = g_svf.high = g_svf.band = g_svf.notch = 0.0f;
    g_svf.freq = 2.0f * sinf(3.14159265f * cutoff / sample_rate);
    g_svf.damp = fminf(2.0f * (1.0f - powf(resonance, 0.25f)), 2.0f);
}}

float svf_process_sample(float in) {{
    /* 2x oversampled internal loop for numerical stability */
    for (int i = 0; i < 2; i++) {{
        g_svf.notch = in - g_svf.damp * g_svf.band;
        g_svf.low   = g_svf.low + g_svf.freq * g_svf.band;
        g_svf.high  = g_svf.notch - g_svf.low;
        g_svf.band  = g_svf.freq * g_svf.high + g_svf.band;
    }}
    return g_svf.{};
}}
"#,
                config.mode, sample_rate, config.cutoff_hz, res, out_member,
            )
        }
        _ => {
            let coeffs = match config.mode {
                ProcessorMode::BiquadHighpass => {
                    biquad_highpass_coeffs(config.cutoff_hz, sample_rate, config.q)
                }
                ProcessorMode::BiquadBandpass => {
                    biquad_bandpass_coeffs(config.cutoff_hz, sample_rate, config.q)
                }
                ProcessorMode::BiquadNotch => {
                    biquad_notch_coeffs(config.cutoff_hz, sample_rate, config.q)
                }
                ProcessorMode::BiquadPeaking => {
                    biquad_peaking_coeffs(config.cutoff_hz, sample_rate, config.q, config.gain_db)
                }
                _ => biquad_lowpass_coeffs(config.cutoff_hz, sample_rate, config.q),
            };

            format!(
                r#"/* Generated by embedded-dsp studio for ARM CMSIS-DSP
 * Algorithm: {:?}
 * Sample Rate: {:.0} Hz | Cutoff: {:.1} Hz | Q: {:.3}
 */

#include "arm_math.h"

/* CMSIS-DSP Biquad Direct Form I coefficients layout:
 * [b0, b1, b2, -a1, -a2]
 */
static const float32_t biquad_coeffs[5] = {{
    {:.8}f,  /* b0 */
    {:.8}f,  /* b1 */
    {:.8}f,  /* b2 */
    {:.8}f,  /* -a1 */
    {:.8}f   /* -a2 */
}};

static float32_t biquad_state[4] = {{0.0f, 0.0f, 0.0f, 0.0f}};
static arm_biquad_casd_df1_inst_f32 filter_instance;

void filter_init(void) {{
    arm_biquad_cascade_df1_init_f32(&filter_instance, 1, (float32_t*)biquad_coeffs, biquad_state);
}}

void filter_process(const float32_t* src, float32_t* dst, uint32_t block_size) {{
    arm_biquad_cascade_df1_f32(&filter_instance, (float32_t*)src, dst, block_size);
}}
"#,
                config.mode,
                sample_rate,
                config.cutoff_hz,
                config.q,
                coeffs[0],
                coeffs[1],
                coeffs[2],
                coeffs[3],
                coeffs[4],
            )
        }
    }
}
