//! MCU C & Rust Codegen View for Target Deployment.
//!
//! Exports zero-allocation, static buffer code for microcontrollers (Cortex-M, RISC-V, ESP32)
//! matching the exact filter design tuned in the studio.

use crate::state::{ProcessorConfig, StudioState};
use eframe::egui;
use embedded_dsp::filter_design::biquad_lowpass_coeffs;

#[derive(Default)]
pub struct CodegenView {
    pub target_language: TargetLanguage,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TargetLanguage {
    #[default]
    RustNoStd,
    CmsisDspC,
}

impl CodegenView {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn show(&mut self, ui: &mut egui::Ui, state: &StudioState) {
        ui.horizontal(|ui| {
            ui.heading("⚡ 6. Zero-Allocation MCU Codegen");
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                ui.selectable_value(
                    &mut self.target_language,
                    TargetLanguage::RustNoStd,
                    "🦀 no_std Rust",
                );
                ui.selectable_value(
                    &mut self.target_language,
                    TargetLanguage::CmsisDspC,
                    "⚙️ CMSIS-DSP C",
                );
            });
        });

        ui.add_space(4.0);
        ui.label(
            "Export ready-to-flash, zero-allocation code tailored for microcontrollers (ARM Cortex-M, \
            RISC-V, ESP32). Copy directly into your firmware project.",
        );
        ui.add_space(8.0);

        let code = match self.target_language {
            TargetLanguage::RustNoStd => generate_rust_code(&state.proc_a, state.sample_rate),
            TargetLanguage::CmsisDspC => generate_c_code(&state.proc_a, state.sample_rate),
        };

        ui.horizontal(|ui| {
            if ui.button("📋 Copy Code to Clipboard").clicked() {
                ui.ctx().copy_text(code.clone());
            }
        });

        ui.add_space(6.0);

        egui::ScrollArea::vertical().show(ui, |ui| {
            ui.add(
                egui::TextEdit::multiline(&mut code.as_str())
                    .font(egui::TextStyle::Monospace)
                    .desired_width(f32::INFINITY)
                    .desired_rows(22)
                    .interactive(false),
            );
        });
    }
}

fn generate_rust_code(config: &ProcessorConfig, sample_rate: f32) -> String {
    let coeffs = biquad_lowpass_coeffs(config.cutoff_hz, sample_rate, config.q);

    format!(
        r#"//! Generated by embedded-dsp studio for no_std MCU deployment
//! Algorithm: {:?}
//! Sample Rate: {:.0} Hz | Cutoff: {:.1} Hz | Q: {:.3}

#![no_std]

use embedded_dsp::filtering::{{biquad_cascade_df1_f32, BiquadCascadeInstanceF32}};

// Precomputed Direct Form I Biquad coefficients: [b0, b1, b2, a1, a2]
pub static BIQUAD_COEFFS: [f32; 5] = [
    {:.8}f32, // b0
    {:.8}f32, // b1
    {:.8}f32, // b2
    {:.8}f32, // a1
    {:.8}f32, // a2
];

pub struct FilterPipeline {{
    state: [f32; 4],
}}

impl FilterPipeline {{
    pub const fn new() -> Self {{
        Self {{
            state: [0.0; 4],
        }}
    }}

    pub fn process_block(&mut self, input: &[f32], output: &mut [f32]) {{
        let mut instance = BiquadCascadeInstanceF32::init(1, &BIQUAD_COEFFS, &mut self.state);
        biquad_cascade_df1_f32(&mut instance, input, output);
    }}
}}
"#,
        config.mode,
        sample_rate,
        config.cutoff_hz,
        config.q,
        coeffs[0],
        coeffs[1],
        coeffs[2],
        coeffs[3],
        coeffs[4],
    )
}

fn generate_c_code(config: &ProcessorConfig, sample_rate: f32) -> String {
    let coeffs = biquad_lowpass_coeffs(config.cutoff_hz, sample_rate, config.q);

    format!(
        r#"/* Generated by embedded-dsp studio for ARM CMSIS-DSP
 * Algorithm: {:?}
 * Sample Rate: {:.0} Hz | Cutoff: {:.1} Hz | Q: {:.3}
 */

#include "arm_math.h"

/* CMSIS-DSP Biquad Direct Form I coefficients layout:
 * [b0, b1, b2, -a1, -a2]
 */
static const float32_t biquad_coeffs[5] = {{
    {:.8}f,  /* b0 */
    {:.8}f,  /* b1 */
    {:.8}f,  /* b2 */
    {:.8}f,  /* -a1 */
    {:.8}f   /* -a2 */
}};

static float32_t biquad_state[4] = {{0.0f, 0.0f, 0.0f, 0.0f}};
static arm_biquad_casd_df1_inst_f32 filter_instance;

void filter_init(void) {{
    arm_biquad_cascade_df1_init_f32(&filter_instance, 1, (float32_t*)biquad_coeffs, biquad_state);
}}

void filter_process(const float32_t* src, float32_t* dst, uint32_t block_size) {{
    arm_biquad_cascade_df1_f32(&filter_instance, (float32_t*)src, dst, block_size);
}}
"#,
        config.mode,
        sample_rate,
        config.cutoff_hz,
        config.q,
        coeffs[0],
        coeffs[1],
        coeffs[2],
        coeffs[3],
        coeffs[4],
    )
}
